{
 "title": "Bitburner",
 "description": "Various Bitburner statistics, updating in real-time",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# Bitburner Grafana graphs\n\nIf a graph ends abruptly, either my internet died or I closed the game lol\n\n- [Client source (fucker suite)](https://github.com/oatmealine/bitburner-scripts/)\n- [Server source](https://github.com/oatmealine/bitburner-grafana)\n\nFurther instructions are available on the repos"
   }
  },
  {
   "title": "everythingfucker - processes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  processes,\n  hacking,\n  weakening,\n  growing\nFROM stats\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bought servers",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ram AS \"time\",\n  ram AS \"RAM\",\n  hostname\nFROM boughtservers\nORDER BY 1"
    }
   ]
  },
  {
   "title": "everythingfucker - Known servers",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  known AS \"unrooted\",\n  rooted,\n  owned,\n  profitable\nFROM servers\nORDER BY 1"
    }
   ]
  }
 ]
}